# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - lib/generated/**
    - "**/*.gr.dart"

  errors:
    # needed for freezed
    invalid_annotation_target: ignore
    # disable suggestion: Don't use 'BuildContext's across async gaps.
    use_build_context_synchronously: ignore

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    depend_on_referenced_packages: false # https://dart-lang.github.io/linter/lints/depend_on_referenced_packages.html
    require_trailing_commas: true # https://dart-lang.github.io/linter/lints/require_trailing_commas.html
    unawaited_futures: true # https://dart-lang.github.io/linter/lints/unawaited_futures.html
    always_use_package_imports: true # https://dart-lang.github.io/linter/lints/always_use_package_imports.html
    cancel_subscriptions: true # https://dart-lang.github.io/linter/lints/cancel_subscriptions.html
    close_sinks: true # https://dart-lang.github.io/linter/lints/close_sinks.html
    always_declare_return_types: true # https://dart-lang.github.io/linter/lints/always_declare_return_types.html
    flutter_style_todos: true # https://dart-lang.github.io/linter/lints/flutter_style_todos.html
    prefer_final_fields: true # https://dart-lang.github.io/linter/lints/prefer_final_fields.html
    prefer_final_locals: true # https://dart-lang.github.io/linter/lints/prefer_final_locals.html
    sort_constructors_first: true # https://dart-lang.github.io/linter/lints/sort_constructors_first.html
    sort_unnamed_constructors_first: true # https://dart-lang.github.io/linter/lints/sort_unnamed_constructors_first.html
    unnecessary_lambdas: true # https://dart-lang.github.io/linter/lints/unnecessary_lambdas.html
    use_enums: true # https://dart-lang.github.io/linter/lints/use_enums.html
    use_super_parameters: true # https://dart-lang.github.io/linter/lints/use_super_parameters.html
    avoid_types_as_parameter_names: true # https://dart-lang.github.io/linter/lints/avoid_types_as_parameter_names.html

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
